apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
  - name: platform-gateway
    namespace: kgateway-system
  hostnames:
  - "argocd.portal.local"
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
