apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-controller
spec:
  template:
    spec:
      containers:
      - name: tekton-pipelines-controller
        env:
        - name: ENTRYPOINT_IMAGE
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.65.0"
        - name: NOP_IMAGE
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.65.0"
        - name: SHELL_IMAGE
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/shell:v0.65.0"
        - name: SHELL_IMAGE_WIN
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/shell:v0.65.0"
        - name: SIDECARLOGRESULTS_IMAGE
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.65.0"
        - name: WORKINGDIRINIT_IMAGE
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.65.0"
