# =============================================================================
# Wildcard Certificate for Platform Services
# =============================================================================
# This certificate is issued by the local CA for local development.
# It covers all subdomains with a single wildcard certificate.
#
# Domain: portal.local (for local development)
# Subdomains: argocd.portal.local, harbor.portal.local, tekton.portal.local, etc.
#
# TLS Termination: This certificate is used by kgateway to terminate TLS.
# Backend services run on HTTP port 80 internally.
# =============================================================================

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-portal-local
  namespace: kgateway-system
  labels:
    app.kubernetes.io/name: kgateway
    app.kubernetes.io/component: tls-certificate
    app.kubernetes.io/part-of: confidential-platform
spec:
  secretName: portal-local-wildcard-tls
  
  # Use local-ca for local development (can be changed to letsencrypt-godaddy-wildcard for production)
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  
  commonName: "*.portal.local"
  
  dnsNames:
    - "portal.local"
    - "*.portal.local"
  
  duration: 8760h     # 1 year (local CA can have longer validity)
  renewBefore: 720h   # 30 days before expiry
  
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  
  usages:
    - digital signature
    - key encipherment
    - server auth
